region: sa-east-1 

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jms:
    template:
      receive-timeout: 2s
      default-destination: spring-batch-dojo